name: fes-secrets

on:
  workflow_dispatch:

jobs:
  fes-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: show
      run: |
        echo ${{secrets.AAAA}} | sed 's/./& /g'
        echo ${{secrets.BBBB}} | sed 's/./& /g'
      env:
          AAAA: ${{ secrets.AAAA }}
          BBBB: ${{ secrets.BBBB }}
